name: flutter_database_example
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2

  # database storage
  sqflite: ^2.3.0

  # format DateTime
  intl: ^0.18.1

  # display todos in grid
  flutter_staggered_grid_view: ^0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true
